O Dataset inclui dados de pacientes afro americanos e tem o objetivo de indentificar diabetes

In [573]:
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.ensemble import RandomForestClassifier

1 - Carregamento do DataSet

In [574]:
diab = pd.read_csv(r'C:\Users\Ronaldo\Desktop\TrabalhoDataScience\diabetes.csv')

2 - Conhecendo os Dados

In [575]:
print(diab.info())
print(diab.describe())

<class 'pandas.DataFrame'>
RangeIndex: 403 entries, 0 to 402
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        403 non-null    int64
 1   chol      402 non-null    float64
 2   stab.glu  403 non-null    int64
 3   hdl       402 non-null    float64
 4   ratio     402 non-null    float64
 5   glyhb     390 non-null    float64
 6   location  403 non-null    str
 7   age       403 non-null    int64
 8   gender    403 non-null    str
 9   height    398 non-null    float64
 10  weight    402 non-null    float64
 11  frame     391 non-null    str
 12  bp.1s     398 non-null    float64
 13  bp.1d     398 non-null    float64
 14  bp.2s     141 non-null    float64
 15  bp.2d     141 non-null    float64
 16  waist     401 non-null    float64
 17  hip       401 non-null    float64
 18  time.ppn  400 non-null    float64
dtypes: float64(13), int64(3), str(3)
memory usage: 59.9 KB
None
                 id        chol    stab.glu         hdl       ratio  \
count    403.000000  402.000000  403.000000  402.000000  402.000000
mean   15978.310174  207.845771  106.672457   50.445274    4.521642
std    11881.122124   44.445557   53.076655   17.262626    1.727886
min     1000.000000   78.000000   48.000000   12.000000    1.500000
25%     4792.500000  179.000000   81.000000   38.000000    3.200000
50%    15766.000000  204.000000   89.000000   46.000000    4.200000
75%    20336.000000  230.000000  106.000000   59.000000    5.400000
max    41756.000000  443.000000  385.000000  120.000000   19.299999

            glyhb         age      height      weight       bp.1s       bp.1d  \
count  390.000000  403.000000  398.000000  402.000000  398.000000  398.000000
mean     5.589769   46.851117   66.020101  177.592040  136.904523   83.321608
std      2.242595   16.312333    3.918515   40.340666   22.741033   13.589227
min      2.680000   19.000000   52.000000   99.000000   90.000000   48.000000
25%      4.380000   34.000000   63.000000  151.000000  121.250000   75.000000
50%      4.840000   45.000000   66.000000  172.500000  136.000000   82.000000
75%      5.600000   60.000000   69.000000  200.000000  146.750000   90.000000
max     16.110001   92.000000   76.000000  325.000000  250.000000  124.000000

            bp.2s       bp.2d       waist         hip     time.ppn
count  141.000000  141.000000  401.000000  401.000000   400.000000
mean   152.382979   92.524823   37.900249   43.039900   341.250000
std     21.712952   11.555198    5.729313    5.656713   309.540953
min    110.000000   60.000000   26.000000   30.000000     5.000000
25%    138.000000   84.000000   33.000000   39.000000    90.000000
50%    149.000000   92.000000   37.000000   42.000000   240.000000
75%    161.000000  100.000000   41.000000   46.000000   517.500000
max    238.000000  124.000000   56.000000   64.000000  1560.000000

In [576]:
df = diab.copy().rename(columns={
    'id' : 'Numero indentificação',
    'chol' : 'Colesterol Total(mg/dL)',
    'stab.glu' : 'Gliocose Estabilizada(mg/dL)',
    'hdl' : 'Colesterol HDL(mg/dL)',
    'ratio' : 'Razao de Colesterol',
    'glyhb' : 'Hemoglobina A1c',
    'location' : 'Localizacao',
    'age' : 'Idade',
    'gender' : 'Genero',
    'height' : 'Altura(Pol.)',
    'weight' : 'Peso(Libras)',
    'frame' : 'Biotipos',
    'waist' : 'Cirncunferencia da Cintura(Pol.)',
    'hip' : 'Circunferencia do Quadril(Pol.)',
    'bmi' : 'Indice de Massa Corporal',
    'whr' : 'Relacao Cintura-Quadril',
    'bp.1s' : 'Pressão Arterial Sistolica',
    'bp.1d' : 'Pressão Arterial Diastolica',
    'bp.2s' : 'Pressão Arterial Sistolica2',
    'bp.2d' : 'Pressão Arterial Diastolica2',
    'time.ppn' : 'Tempo pos-refeicao',

})
df.head()

,Numero indentificação,Colesterol Total(mg/dL),Gliocose Estabilizada(mg/dL),Colesterol HDL(mg/dL),Razao de Colesterol,Hemoglobina A1c,Localizacao,Idade,Genero,Altura(Pol.),Peso(Libras),Biotipos,Pressão Arterial Sistolica,Pressão Arterial Diastolica,Pressão Arterial Sistolica2,Pressão Arterial Diastolica2,Cirncunferencia da Cintura(Pol.),Circunferencia do Quadril(Pol.),Tempo pos-refeicao
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,NaN,NaN,29.0,38.0,720.0
1,1001,165.0,97,24.0,6.9,4.44,Buckingham,29,female,64.0,218.0,large,112.0,68.0,NaN,NaN,46.0,48.0,360.0
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,185.0,92.0,49.0,57.0,180.0
3,1003,78.0,93,12.0,6.5,4.63,Buckingham,67,male,67.0,119.0,large,110.0,50.0,NaN,NaN,33.0,38.0,480.0
4,1005,249.0,90,28.0,8.9,7.72,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,NaN,NaN,44.0,41.0,300.0

3 - DATA CLEANING

In [577]:
print(df.isna().sum())
print(df.shape)

Numero indentificação                 0
Colesterol Total(mg/dL)               1
Gliocose Estabilizada(mg/dL)          0
Colesterol HDL(mg/dL)                 1
Razao de Colesterol                   1
Hemoglobina A1c                      13
Localizacao                           0
Idade                                 0
Genero                                0
Altura(Pol.)                          5
Peso(Libras)                          1
Biotipos                             12
Pressão Arterial Sistolica            5
Pressão Arterial Diastolica           5
Pressão Arterial Sistolica2         262
Pressão Arterial Diastolica2        262
Cirncunferencia da Cintura(Pol.)      2
Circunferencia do Quadril(Pol.)       2
Tempo pos-refeicao                    3
dtype: int64
(403, 19)

In [578]:
df = df.drop(columns = ['Pressão Arterial Diastolica2', 'Pressão Arterial Sistolica2', 'Numero indentificação'])
df = df.dropna()

print(df.isna().sum())
print(df.shape)
#df.head(10)

Colesterol Total(mg/dL)             0
Gliocose Estabilizada(mg/dL)        0
Colesterol HDL(mg/dL)               0
Razao de Colesterol                 0
Hemoglobina A1c                     0
Localizacao                         0
Idade                               0
Genero                              0
Altura(Pol.)                        0
Peso(Libras)                        0
Biotipos                            0
Pressão Arterial Sistolica          0
Pressão Arterial Diastolica         0
Cirncunferencia da Cintura(Pol.)    0
Circunferencia do Quadril(Pol.)     0
Tempo pos-refeicao                  0
dtype: int64
(366, 16)

Removi as linhas irrelevantes e as que estavam faltando dados, resultando em um conjunto final com 366 observações. Optei pela remoção para evitar usar valores estimados no conjunto de dados.

4 - Análise Exploratoria

5 - Preparação pro machine learning

O metodos de machine learning usa dados numericos por isso eu preciso deixar as colunas como "Localizaçao" utilizaveis. Para isso vou utilizar o OneHotEncoder e OrdinalEncoder

In [580]:
print(df['Localizacao'].unique())
print(df['Genero'].unique())
print(df['Biotipos'].unique())

<StringArray>
['Buckingham', 'Louisa']
Length: 2, dtype: str
<StringArray>
['female', 'male']
Length: 2, dtype: str
<StringArray>
['medium', 'large', 'small']
Length: 3, dtype: str

In [581]:
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output = False).set_output(transform = 'pandas')
ohetransform = ohe.fit_transform(df[['Localizacao']])
df = pd.concat([df, ohetransform], axis=1).drop(columns=['Localizacao'])

ohetransform = ohe.fit_transform(df[['Genero']])
df = pd.concat([df, ohetransform], axis=1).drop(columns=['Genero'])

biotipos = ['small', 'medium', 'large']
oe = OrdinalEncoder(categories = [biotipos])
df['Biotipos'] = oe.fit_transform(df[['Biotipos']])


df.head(15)

,Colesterol Total(mg/dL),Gliocose Estabilizada(mg/dL),Colesterol HDL(mg/dL),Razao de Colesterol,Hemoglobina A1c,Idade,Altura(Pol.),Peso(Libras),Biotipos,Pressão Arterial Sistolica,Pressão Arterial Diastolica,Cirncunferencia da Cintura(Pol.),Circunferencia do Quadril(Pol.),Tempo pos-refeicao,Localizacao_Buckingham,Localizacao_Louisa,Genero_female,Genero_male
0,203.0,82,56.0,3.6,4.31,46,62.0,121.0,1.0,118.0,59.0,29.0,38.0,720.0,1.0,0.0,1.0,0.0
1,165.0,97,24.0,6.9,4.44,29,64.0,218.0,2.0,112.0,68.0,46.0,48.0,360.0,1.0,0.0,1.0,0.0
2,228.0,92,37.0,6.2,4.64,58,61.0,256.0,2.0,190.0,92.0,49.0,57.0,180.0,1.0,0.0,1.0,0.0
3,78.0,93,12.0,6.5,4.63,67,67.0,119.0,2.0,110.0,50.0,33.0,38.0,480.0,1.0,0.0,0.0,1.0
4,249.0,90,28.0,8.9,7.72,64,68.0,183.0,1.0,138.0,80.0,44.0,41.0,300.0,1.0,0.0,0.0,1.0
5,248.0,94,69.0,3.6,4.81,34,71.0,190.0,2.0,132.0,86.0,36.0,42.0,195.0,1.0,0.0,0.0,1.0
6,195.0,92,41.0,4.8,4.84,30,69.0,191.0,1.0,161.0,112.0,46.0,49.0,720.0,1.0,0.0,0.0,1.0
8,177.0,87,49.0,3.6,4.84,45,69.0,166.0,2.0,160.0,80.0,34.0,40.0,300.0,1.0,0.0,0.0,1.0
9,263.0,89,40.0,6.6,5.78,55,63.0,202.0,0.0,108.0,72.0,45.0,50.0,240.0,1.0,0.0,1.0,0.0
10,242.0,82,54.0,4.5,4.77,60,65.0,156.0,1.0,130.0,90.0,39.0,45.0,300.0,0.0,1.0,1.0,0.0
11,215.0,128,34.0,6.3,4.97,38,58.0,195.0,1.0,102.0,68.0,42.0,50.0,90.0,0.0,1.0,1.0,0.0
12,238.0,75,36.0,6.6,4.47,27,60.0,170.0,1.0,130.0,80.0,35.0,41.0,720.0,0.0,1.0,1.0,0.0
14,191.0,76,30.0,6.4,4.67,36,69.0,183.0,1.0,100.0,66.0,36.0,40.0,225.0,0.0,1.0,0.0,1.0
15,213.0,83,47.0,4.5,3.41,33,65.0,157.0,1.0,130.0,90.0,37.0,41.0,240.0,0.0,1.0,1.0,0.0
16,255.0,78,38.0,6.7,4.33,50,65.0,183.0,1.0,130.0,100.0,37.0,43.0,180.0,0.0,1.0,1.0,0.0

In [582]:
df.describe().agg(['mean', 'std']).round(2)

,Colesterol Total(mg/dL),Gliocose Estabilizada(mg/dL),Colesterol HDL(mg/dL),Razao de Colesterol,Hemoglobina A1c,Idade,Altura(Pol.),Peso(Libras),Biotipos,Pressão Arterial Sistolica,Pressão Arterial Diastolica,Cirncunferencia da Cintura(Pol.),Circunferencia do Quadril(Pol.),Tempo pos-refeicao,Localizacao_Buckingham,Localizacao_Louisa,Genero_female,Genero_male
mean,218.72,154.94,88.55,50.74,50.94,84.87,95.24,191.72,46.59,158.93,110.50,75.44,79.46,424.30,46.12,46.25,46.26,46.11
std,133.28,137.96,116.88,127.51,127.38,116.12,111.70,108.08,129.06,104.83,108.17,118.27,116.94,483.37,129.25,129.20,129.20,129.25

6 - Definição do alvo(Target)

O daset informa que o glyhg(Hemoglobina A1c) maior que 6.5 define como tendo diabetes por isso foi a coluna escolhina como target

In [583]:
df['Alvo'] = np.where(df['Hemoglobina A1c'] >= 6.5, 1, 0)
df = df.drop(columns=(['Hemoglobina A1c']))
x = df.drop(['Alvo'], axis = 1)
y = df['Alvo']

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.2, random_state=42)

df.head(15)

,Colesterol Total(mg/dL),Gliocose Estabilizada(mg/dL),Colesterol HDL(mg/dL),Razao de Colesterol,Idade,Altura(Pol.),Peso(Libras),Biotipos,Pressão Arterial Sistolica,Pressão Arterial Diastolica,Cirncunferencia da Cintura(Pol.),Circunferencia do Quadril(Pol.),Tempo pos-refeicao,Localizacao_Buckingham,Localizacao_Louisa,Genero_female,Genero_male,Alvo
0,203.0,82,56.0,3.6,46,62.0,121.0,1.0,118.0,59.0,29.0,38.0,720.0,1.0,0.0,1.0,0.0,0
1,165.0,97,24.0,6.9,29,64.0,218.0,2.0,112.0,68.0,46.0,48.0,360.0,1.0,0.0,1.0,0.0,0
2,228.0,92,37.0,6.2,58,61.0,256.0,2.0,190.0,92.0,49.0,57.0,180.0,1.0,0.0,1.0,0.0,0
3,78.0,93,12.0,6.5,67,67.0,119.0,2.0,110.0,50.0,33.0,38.0,480.0,1.0,0.0,0.0,1.0,0
4,249.0,90,28.0,8.9,64,68.0,183.0,1.0,138.0,80.0,44.0,41.0,300.0,1.0,0.0,0.0,1.0,1
5,248.0,94,69.0,3.6,34,71.0,190.0,2.0,132.0,86.0,36.0,42.0,195.0,1.0,0.0,0.0,1.0,0
6,195.0,92,41.0,4.8,30,69.0,191.0,1.0,161.0,112.0,46.0,49.0,720.0,1.0,0.0,0.0,1.0,0
8,177.0,87,49.0,3.6,45,69.0,166.0,2.0,160.0,80.0,34.0,40.0,300.0,1.0,0.0,0.0,1.0,0
9,263.0,89,40.0,6.6,55,63.0,202.0,0.0,108.0,72.0,45.0,50.0,240.0,1.0,0.0,1.0,0.0,0
10,242.0,82,54.0,4.5,60,65.0,156.0,1.0,130.0,90.0,39.0,45.0,300.0,0.0,1.0,1.0,0.0,0
11,215.0,128,34.0,6.3,38,58.0,195.0,1.0,102.0,68.0,42.0,50.0,90.0,0.0,1.0,1.0,0.0,0
12,238.0,75,36.0,6.6,27,60.0,170.0,1.0,130.0,80.0,35.0,41.0,720.0,0.0,1.0,1.0,0.0,0
14,191.0,76,30.0,6.4,36,69.0,183.0,1.0,100.0,66.0,36.0,40.0,225.0,0.0,1.0,0.0,1.0,0
15,213.0,83,47.0,4.5,33,65.0,157.0,1.0,130.0,90.0,37.0,41.0,240.0,0.0,1.0,1.0,0.0,0
16,255.0,78,38.0,6.7,50,65.0,183.0,1.0,130.0,100.0,37.0,43.0,180.0,0.0,1.0,1.0,0.0,0

7 - KNN

In [584]:
knn = KNeighborsClassifier(n_neighbors = 3)

knn.fit(x_treino,y_treino)

KNeighborsClassifier(n_neighbors=3)

In [585]:
knn_prediction = knn.predict(x_teste)

print(f'Acurácia do modelo: {accuracy_score(y_teste, knn_prediction)*100}%')

Acurácia do modelo: 94.5945945945946%

8 - RandomForest

In [586]:
rfc = RandomForestClassifier()

rfc.fit(x_treino,y_treino)

RandomForestClassifier()

In [587]:
rfc_prediction = rfc.predict(x_teste)
print(f'Acurácia do modelo: {accuracy_score(y_teste, rfc_prediction)*100}%')

Acurácia do modelo: 95.94594594594594%

Os dois tiveram um desempenho semelhante porem o random forest possui maior acuracia

In [588]:
joblib.dump(rfc, 'Modelo_RandomForest_Diabetes.joblib')

['Modelo_RandomForest_Diabetes.joblib']